GET http://localhost:3000/api/stores/nearby
  ?lat=51.47
  &lng=0.07
  &distance=5000
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViNTg1OTBhMzhhMDM5ZjBiYWZhNDNmNCIsImlhdCI6MTUzMjUxNjY3OCwiZXhwIjoxNTMyNjAzMDc4fQ.Pvp3IGUTY1QstzU2DE-q0Xn-CtBw6lDNSp00opu6ElQ

###

POST http://localhost:3000/api/auth/register
content-type: application/json

{
  "email": "demo@user.it",
  "name": "demo",
  "password": "12345678"
}


###
POST http://localhost:3000/api/auth/login
content-type: application/json

{
  "email": "demo@user.it",
  "password": "12345678"
}


###

POST http://localhost:3000/api/stores/ 
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViNTg1OTBhMzhhMDM5ZjBiYWZhNDNmNCIsImlhdCI6MTUzMjUxNjY3OCwiZXhwIjoxNTMyNjAzMDc4fQ.Pvp3IGUTY1QstzU2DE-q0Xn-CtBw6lDNSp00opu6ElQ

{
  "name": "Woolwich - Powis Street",
  "address": {
    "street": "32, POWIS STREET",
    "city": "Woolwich",
    "province": "ENG",
    "zipcode": "SE18 6LF"
  },
  "lat": 51.47,
  "lng": 0.07
}